package entities;
// Generated Apr 25, 2018 3:42:43 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name = "categoria", catalog = "db_inv_freel", uniqueConstraints = @UniqueConstraint(columnNames = "NOME"))
public class Categoria implements java.io.Serializable, entities.Entity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer rowId;
	private String nome;
	private Integer rowIdPadre;
	private Set<Tag> tags = new HashSet<Tag>(0);

	public Categoria() {
	}

	public Categoria(String nome) {
		this.nome = nome;
	}

	public Categoria(String nome, Integer rowIdPadre, Set<Tag> tags) {
		this.nome = nome;
		this.rowIdPadre = rowIdPadre;
		this.tags = tags;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ROW_ID", unique = true, nullable = false)
	public Integer getRowId() {
		return this.rowId;
	}

	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}

	@Column(name = "NOME", unique = true, nullable = false, length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "ROW_ID_PADRE")
	public Integer getRowIdPadre() {
		return this.rowIdPadre;
	}

	public void setRowIdPadre(Integer rowIdPadre) {
		this.rowIdPadre = rowIdPadre;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "tag_categoria", catalog = "db_inv_freel", joinColumns = {
			@JoinColumn(name = "ROW_ID_CATEGORIA", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "TAG", nullable = false, updatable = false) })
	public Set<Tag> getTags() {
		return this.tags;
	}

	public void setTags(Set<Tag> tags) {
		this.tags = tags;
	}

}
