package entities;
// Generated Apr 25, 2018 3:42:43 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Fattura generated by hbm2java
 */
@Entity
@Table(name = "fattura", catalog = "db_inv_freel", uniqueConstraints = @UniqueConstraint(columnNames = "NUMERO"))
public class Fattura implements java.io.Serializable, entities.Entity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer rowId;
	private TipologiaFattura tipologiaFattura;
	private Utente utente;
	private String numero;
	private String fatturaDifferita;
	private Date dataEmissione;
	private String intestazione;
	private String luogoDesinazione;
	private String cfPivaUtente;
	private String modalitaPagamento;
	private String banca;
	private float imponibile1;
	private float imponibile2;
	private float imponibile3;
	private float imponibile4;
	private float imposta1;
	private float imposta2;
	private float imposta3;
	private float imposta4;
	private String annotazioni;
	private Date dataChiusura;
	private Set<ElementoFattura> elementoFatturas = new HashSet<ElementoFattura>(0);

	public Fattura() {
	}

	public Fattura(TipologiaFattura tipologiaFattura, Utente utente, String numero, Date dataEmissione,
			String intestazione, String luogoDesinazione, String cfPivaUtente, String modalitaPagamento,
			float imponibile1, float imponibile2, float imponibile3, float imponibile4, float imposta1, float imposta2,
			float imposta3, float imposta4) {
		this.tipologiaFattura = tipologiaFattura;
		this.utente = utente;
		this.numero = numero;
		this.dataEmissione = dataEmissione;
		this.intestazione = intestazione;
		this.luogoDesinazione = luogoDesinazione;
		this.cfPivaUtente = cfPivaUtente;
		this.modalitaPagamento = modalitaPagamento;
		this.imponibile1 = imponibile1;
		this.imponibile2 = imponibile2;
		this.imponibile3 = imponibile3;
		this.imponibile4 = imponibile4;
		this.imposta1 = imposta1;
		this.imposta2 = imposta2;
		this.imposta3 = imposta3;
		this.imposta4 = imposta4;
	}

	public Fattura(TipologiaFattura tipologiaFattura, Utente utente, String numero, String fatturaDifferita,
			Date dataEmissione, String intestazione, String luogoDesinazione, String cfPivaUtente,
			String modalitaPagamento, String banca, float imponibile1, float imponibile2, float imponibile3,
			float imponibile4, float imposta1, float imposta2, float imposta3, float imposta4, String annotazioni,
			Date dataChiusura, Set<ElementoFattura> elementoFatturas) {
		this.tipologiaFattura = tipologiaFattura;
		this.utente = utente;
		this.numero = numero;
		this.fatturaDifferita = fatturaDifferita;
		this.dataEmissione = dataEmissione;
		this.intestazione = intestazione;
		this.luogoDesinazione = luogoDesinazione;
		this.cfPivaUtente = cfPivaUtente;
		this.modalitaPagamento = modalitaPagamento;
		this.banca = banca;
		this.imponibile1 = imponibile1;
		this.imponibile2 = imponibile2;
		this.imponibile3 = imponibile3;
		this.imponibile4 = imponibile4;
		this.imposta1 = imposta1;
		this.imposta2 = imposta2;
		this.imposta3 = imposta3;
		this.imposta4 = imposta4;
		this.annotazioni = annotazioni;
		this.dataChiusura = dataChiusura;
		this.elementoFatturas = elementoFatturas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ROW_ID", unique = true, nullable = false)
	public Integer getRowId() {
		return this.rowId;
	}

	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIPOLOGIA", nullable = false)
	public TipologiaFattura getTipologiaFattura() {
		return this.tipologiaFattura;
	}

	public void setTipologiaFattura(TipologiaFattura tipologiaFattura) {
		this.tipologiaFattura = tipologiaFattura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_UTENTE", nullable = false)
	public Utente getUtente() {
		return this.utente;
	}

	public void setUtente(Utente utente) {
		this.utente = utente;
	}

	@Column(name = "NUMERO", unique = true, nullable = false, length = 45)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "FATTURA_DIFFERITA", length = 45)
	public String getFatturaDifferita() {
		return this.fatturaDifferita;
	}

	public void setFatturaDifferita(String fatturaDifferita) {
		this.fatturaDifferita = fatturaDifferita;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_EMISSIONE", nullable = false, length = 19)
	public Date getDataEmissione() {
		return this.dataEmissione;
	}

	public void setDataEmissione(Date dataEmissione) {
		this.dataEmissione = dataEmissione;
	}

	@Column(name = "INTESTAZIONE", nullable = false, length = 250)
	public String getIntestazione() {
		return this.intestazione;
	}

	public void setIntestazione(String intestazione) {
		this.intestazione = intestazione;
	}

	@Column(name = "LUOGO_DESINAZIONE", nullable = false, length = 250)
	public String getLuogoDesinazione() {
		return this.luogoDesinazione;
	}

	public void setLuogoDesinazione(String luogoDesinazione) {
		this.luogoDesinazione = luogoDesinazione;
	}

	@Column(name = "CF_PIVA_UTENTE", nullable = false, length = 45)
	public String getCfPivaUtente() {
		return this.cfPivaUtente;
	}

	public void setCfPivaUtente(String cfPivaUtente) {
		this.cfPivaUtente = cfPivaUtente;
	}

	@Column(name = "MODALITA_PAGAMENTO", nullable = false, length = 45)
	public String getModalitaPagamento() {
		return this.modalitaPagamento;
	}

	public void setModalitaPagamento(String modalitaPagamento) {
		this.modalitaPagamento = modalitaPagamento;
	}

	@Column(name = "BANCA", length = 250)
	public String getBanca() {
		return this.banca;
	}

	public void setBanca(String banca) {
		this.banca = banca;
	}

	@Column(name = "IMPONIBILE_1", nullable = false, precision = 12, scale = 0)
	public float getImponibile1() {
		return this.imponibile1;
	}

	public void setImponibile1(float imponibile1) {
		this.imponibile1 = imponibile1;
	}

	@Column(name = "IMPONIBILE_2", nullable = false, precision = 12, scale = 0)
	public float getImponibile2() {
		return this.imponibile2;
	}

	public void setImponibile2(float imponibile2) {
		this.imponibile2 = imponibile2;
	}

	@Column(name = "IMPONIBILE_3", nullable = false, precision = 12, scale = 0)
	public float getImponibile3() {
		return this.imponibile3;
	}

	public void setImponibile3(float imponibile3) {
		this.imponibile3 = imponibile3;
	}

	@Column(name = "IMPONIBILE_4", nullable = false, precision = 12, scale = 0)
	public float getImponibile4() {
		return this.imponibile4;
	}

	public void setImponibile4(float imponibile4) {
		this.imponibile4 = imponibile4;
	}

	@Column(name = "IMPOSTA_1", nullable = false, precision = 12, scale = 0)
	public float getImposta1() {
		return this.imposta1;
	}

	public void setImposta1(float imposta1) {
		this.imposta1 = imposta1;
	}

	@Column(name = "IMPOSTA_2", nullable = false, precision = 12, scale = 0)
	public float getImposta2() {
		return this.imposta2;
	}

	public void setImposta2(float imposta2) {
		this.imposta2 = imposta2;
	}

	@Column(name = "IMPOSTA_3", nullable = false, precision = 12, scale = 0)
	public float getImposta3() {
		return this.imposta3;
	}

	public void setImposta3(float imposta3) {
		this.imposta3 = imposta3;
	}

	@Column(name = "IMPOSTA_4", nullable = false, precision = 12, scale = 0)
	public float getImposta4() {
		return this.imposta4;
	}

	public void setImposta4(float imposta4) {
		this.imposta4 = imposta4;
	}

	@Column(name = "ANNOTAZIONI", length = 250)
	public String getAnnotazioni() {
		return this.annotazioni;
	}

	public void setAnnotazioni(String annotazioni) {
		this.annotazioni = annotazioni;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_CHIUSURA", length = 19)
	public Date getDataChiusura() {
		return this.dataChiusura;
	}

	public void setDataChiusura(Date dataChiusura) {
		this.dataChiusura = dataChiusura;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fattura")
	public Set<ElementoFattura> getElementoFatturas() {
		return this.elementoFatturas;
	}

	public void setElementoFatturas(Set<ElementoFattura> elementoFatturas) {
		this.elementoFatturas = elementoFatturas;
	}

}
