package entities;
// Generated Apr 25, 2018 3:42:43 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Feedback generated by hbm2java
 */
@Entity
@Table(name = "feedback", catalog = "db_inv_freel")
public class Feedback implements java.io.Serializable {

	private Integer rowId;
	private Progetto progetto;
	private Utente utenteByRicevutoDa;
	private Utente utenteByRilasciatoDa;
	private int valutazione;
	private String commento;
	private String replica;
	private Date timestampCreazione;

	public Feedback() {
	}

	public Feedback(Progetto progetto, Utente utenteByRicevutoDa, Utente utenteByRilasciatoDa, int valutazione,
			Date timestampCreazione) {
		this.progetto = progetto;
		this.utenteByRicevutoDa = utenteByRicevutoDa;
		this.utenteByRilasciatoDa = utenteByRilasciatoDa;
		this.valutazione = valutazione;
		this.timestampCreazione = timestampCreazione;
	}

	public Feedback(Progetto progetto, Utente utenteByRicevutoDa, Utente utenteByRilasciatoDa, int valutazione,
			String commento, String replica, Date timestampCreazione) {
		this.progetto = progetto;
		this.utenteByRicevutoDa = utenteByRicevutoDa;
		this.utenteByRilasciatoDa = utenteByRilasciatoDa;
		this.valutazione = valutazione;
		this.commento = commento;
		this.replica = replica;
		this.timestampCreazione = timestampCreazione;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ROW_ID", unique = true, nullable = false)
	public Integer getRowId() {
		return this.rowId;
	}

	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PROGETTO", nullable = false)
	public Progetto getProgetto() {
		return this.progetto;
	}

	public void setProgetto(Progetto progetto) {
		this.progetto = progetto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RICEVUTO_DA", nullable = false)
	public Utente getUtenteByRicevutoDa() {
		return this.utenteByRicevutoDa;
	}

	public void setUtenteByRicevutoDa(Utente utenteByRicevutoDa) {
		this.utenteByRicevutoDa = utenteByRicevutoDa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RILASCIATO_DA", nullable = false)
	public Utente getUtenteByRilasciatoDa() {
		return this.utenteByRilasciatoDa;
	}

	public void setUtenteByRilasciatoDa(Utente utenteByRilasciatoDa) {
		this.utenteByRilasciatoDa = utenteByRilasciatoDa;
	}

	@Column(name = "VALUTAZIONE", nullable = false)
	public int getValutazione() {
		return this.valutazione;
	}

	public void setValutazione(int valutazione) {
		this.valutazione = valutazione;
	}

	@Column(name = "COMMENTO")
	public String getCommento() {
		return this.commento;
	}

	public void setCommento(String commento) {
		this.commento = commento;
	}

	@Column(name = "REPLICA")
	public String getReplica() {
		return this.replica;
	}

	public void setReplica(String replica) {
		this.replica = replica;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TIMESTAMP_CREAZIONE", nullable = false, length = 19)
	public Date getTimestampCreazione() {
		return this.timestampCreazione;
	}

	public void setTimestampCreazione(Date timestampCreazione) {
		this.timestampCreazione = timestampCreazione;
	}

}
