package entities;
// Generated Apr 25, 2018 3:42:43 PM by Hibernate Tools 5.1.0.Alpha1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * File generated by hbm2java
 */
@Entity
@Table(name = "file", catalog = "db_inv_freel")
public class File implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int rowId;
	private String pathFile;
	private Date timestampCreazione;
	private Date timestampModifica;
	private Set<Messaggio> messaggios = new HashSet<Messaggio>(0);
	private Set<Progetto> progettos = new HashSet<Progetto>(0);

	public File() {
	}

	public File(Integer rowId, Date timestampCreazione, Date timestampModifica) {
		this.rowId = rowId;
		this.timestampCreazione = timestampCreazione;
		this.timestampModifica = timestampModifica;
	}

	public File(Integer rowId, Date timestampCreazione, Date timestampModifica, Set<Messaggio> messaggios,
			Set<Progetto> progettos) {
		this.rowId = rowId;
		this.timestampCreazione = timestampCreazione;
		this.timestampModifica = timestampModifica;
		this.messaggios = messaggios;
		this.progettos = progettos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ROW_ID", unique = true, nullable = false)
	public Integer getRowId() {
		return this.rowId;
	}

	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TIMESTAMP_CREAZIONE", nullable = false, length = 19)
	public Date getTimestampCreazione() {
		return this.timestampCreazione;
	}

	public void setTimestampCreazione(Date timestampCreazione) {
		this.timestampCreazione = timestampCreazione;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TIMESTAMP_MODIFICA", nullable = false, length = 19)
	public Date getTimestampModifica() {
		return this.timestampModifica;
	}

	public void setTimestampModifica(Date timestampModifica) {
		this.timestampModifica = timestampModifica;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "file_messaggio", catalog = "db_inv_freel", joinColumns = {
			@JoinColumn(name = "ROW_ID_FILE", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ROW_ID_MESSAGGIO", nullable = false, updatable = false),
					@JoinColumn(name = "ID_PROGETTO_MESSAGGIO", nullable = false, updatable = false)})
	public Set<Messaggio> getMessaggios() {
		return this.messaggios;
	}

	public void setMessaggios(Set<Messaggio> messaggios) {
		this.messaggios = messaggios;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "file_progetto", catalog = "db_inv_freel", joinColumns = {
			@JoinColumn(name = "ROW_ID_FILE", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ROW_ID_PROGETTO", nullable = false, updatable = false) })
	public Set<Progetto> getProgettos() {
		return this.progettos;
	}

	public void setProgettos(Set<Progetto> progettos) {
		this.progettos = progettos;
	}

	@Column(name = "PATH_FILE", unique = true, nullable = false, length = 255)
	public String getPathFile() {
		return pathFile;
	}

	public void setPathFile(String pathFile) {
		this.pathFile = pathFile;
	}

}
