package entities;
// Generated Apr 25, 2018 3:42:43 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Iva generated by hbm2java
 */
@Entity
@Table(name = "iva", catalog = "db_inv_freel")
public class Iva implements java.io.Serializable {

	private float iva;
	private Set<ElementoFattura> elementoFatturas = new HashSet<ElementoFattura>(0);

	public Iva() {
	}

	public Iva(float iva) {
		this.iva = iva;
	}

	public Iva(float iva, Set<ElementoFattura> elementoFatturas) {
		this.iva = iva;
		this.elementoFatturas = elementoFatturas;
	}

	@Id

	@Column(name = "IVA", unique = true, nullable = false, precision = 12, scale = 0)
	public float getIva() {
		return this.iva;
	}

	public void setIva(float iva) {
		this.iva = iva;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "iva")
	public Set<ElementoFattura> getElementoFatturas() {
		return this.elementoFatturas;
	}

	public void setElementoFatturas(Set<ElementoFattura> elementoFatturas) {
		this.elementoFatturas = elementoFatturas;
	}

}
