package entities;
// Generated Apr 25, 2018 3:42:43 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Log generated by hbm2java
 */
@Entity
@Table(name = "log", catalog = "db_inv_freel")
public class Log implements java.io.Serializable {

	private Integer rowId;
	private int rifId;
	private String idSottoinsieme;
	private String testo;
	private String idTransazione;
	private Date dataCreazione;

	public Log() {
	}

	public Log(int rifId, String idSottoinsieme, Date dataCreazione) {
		this.rifId = rifId;
		this.idSottoinsieme = idSottoinsieme;
		this.dataCreazione = dataCreazione;
	}

	public Log(int rifId, String idSottoinsieme, String testo, String idTransazione, Date dataCreazione) {
		this.rifId = rifId;
		this.idSottoinsieme = idSottoinsieme;
		this.testo = testo;
		this.idTransazione = idTransazione;
		this.dataCreazione = dataCreazione;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ROW_ID", unique = true, nullable = false)
	public Integer getRowId() {
		return this.rowId;
	}

	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}

	@Column(name = "RIF_ID", nullable = false)
	public int getRifId() {
		return this.rifId;
	}

	public void setRifId(int rifId) {
		this.rifId = rifId;
	}

	@Column(name = "ID_SOTTOINSIEME", nullable = false, length = 45)
	public String getIdSottoinsieme() {
		return this.idSottoinsieme;
	}

	public void setIdSottoinsieme(String idSottoinsieme) {
		this.idSottoinsieme = idSottoinsieme;
	}

	@Column(name = "TESTO", length = 65535)
	public String getTesto() {
		return this.testo;
	}

	public void setTesto(String testo) {
		this.testo = testo;
	}

	@Column(name = "ID_TRANSAZIONE", length = 45)
	public String getIdTransazione() {
		return this.idTransazione;
	}

	public void setIdTransazione(String idTransazione) {
		this.idTransazione = idTransazione;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_CREAZIONE", nullable = false, length = 19)
	public Date getDataCreazione() {
		return this.dataCreazione;
	}

	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

}
