package entities;
// Generated Apr 25, 2018 3:42:43 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MessaggioId generated by hbm2java
 */
@Embeddable
public class MessaggioId implements java.io.Serializable, entities.Entity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int rowId;
	private int idProgetto;

	public MessaggioId() {
	}

	public MessaggioId(int rowId, int idProgetto) {
		this.rowId = rowId;
		this.idProgetto = idProgetto;
	}

	@Column(name = "ROW_ID", nullable = false)
	public int getRowId() {
		return this.rowId;
	}

	public void setRowId(int rowId) {
		this.rowId = rowId;
	}

	@Column(name = "ID_PROGETTO", nullable = false)
	public int getIdProgetto() {
		return this.idProgetto;
	}

	public void setIdProgetto(int idProgetto) {
		this.idProgetto = idProgetto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MessaggioId))
			return false;
		MessaggioId castOther = (MessaggioId) other;

		return (this.getRowId() == castOther.getRowId()) && (this.getIdProgetto() == castOther.getIdProgetto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRowId();
		result = 37 * result + this.getIdProgetto();
		return result;
	}

}
