package entities;
// Generated Apr 25, 2018 3:42:43 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Messaggio generated by hbm2java
 */
@Entity
@Table(name = "messaggio", catalog = "db_inv_freel")
public class Messaggio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private MessaggioId id;
	private Progetto progetto;
	private Utente utenteByIdMittente;
	private Utente utenteByIdDestinatario;
	private String oggetto;
	private String corpo;
	private Date dataCreazione;
	private Date dataModifica;
	private Set<File> files = new HashSet<File>(0);

	public Messaggio() {
	}

	public Messaggio(MessaggioId id, Progetto progetto, Utente utenteByIdMittente, Utente utenteByIdDestinatario,
			String corpo) {
		this.id = id;
		this.progetto = progetto;
		this.utenteByIdMittente = utenteByIdMittente;
		this.utenteByIdDestinatario = utenteByIdDestinatario;
		this.corpo = corpo;
	}

	public Messaggio(MessaggioId id, Progetto progetto, Utente utenteByIdMittente, Utente utenteByIdDestinatario,
			String oggetto, String corpo, Date dataCreazione, Date dataModifica, Set<File> files) {
		this.id = id;
		this.progetto = progetto;
		this.utenteByIdMittente = utenteByIdMittente;
		this.utenteByIdDestinatario = utenteByIdDestinatario;
		this.oggetto = oggetto;
		this.corpo = corpo;
		this.dataCreazione = dataCreazione;
		this.dataModifica = dataModifica;
		this.files = files;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "rowId", column = @Column(name = "ROW_ID", nullable = false)),
			@AttributeOverride(name = "idProgetto", column = @Column(name = "ID_PROGETTO", nullable = false)) })
	public MessaggioId getId() {
		return this.id;
	}

	public void setId(MessaggioId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PROGETTO", nullable = false, insertable = false, updatable = false)
	public Progetto getProgetto() {
		return this.progetto;
	}

	public void setProgetto(Progetto progetto) {
		this.progetto = progetto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MITTENTE", nullable = false)
	public Utente getUtenteByIdMittente() {
		return this.utenteByIdMittente;
	}

	public void setUtenteByIdMittente(Utente utenteByIdMittente) {
		this.utenteByIdMittente = utenteByIdMittente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_DESTINATARIO", nullable = false)
	public Utente getUtenteByIdDestinatario() {
		return this.utenteByIdDestinatario;
	}

	public void setUtenteByIdDestinatario(Utente utenteByIdDestinatario) {
		this.utenteByIdDestinatario = utenteByIdDestinatario;
	}

	@Column(name = "OGGETTO", length = 200)
	public String getOggetto() {
		return this.oggetto;
	}

	public void setOggetto(String oggetto) {
		this.oggetto = oggetto;
	}

	@Column(name = "CORPO", nullable = false, length = 65535)
	public String getCorpo() {
		return this.corpo;
	}

	public void setCorpo(String corpo) {
		this.corpo = corpo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_CREAZIONE", length = 19)
	public Date getDataCreazione() {
		return this.dataCreazione;
	}

	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_MODIFICA", length = 19)
	public Date getDataModifica() {
		return this.dataModifica;
	}

	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "file_messaggio", catalog = "db_inv_freel", joinColumns = {
			@JoinColumn(name = "ROW_ID_MESSAGGIO", referencedColumnName = "ROW_ID", nullable = false, updatable = false),
			@JoinColumn(name = "ROW_ID_PROGETTO_MESSAGGIO", referencedColumnName = "ID_PROGETTO", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ROW_ID_FILE", referencedColumnName = "ROW_ID", nullable = false, updatable = false) })
	public Set<File> getFiles() {
		return this.files;
	}

	public void setFiles(Set<File> files) {
		this.files = files;
	}

}
