package entities;
// Generated Apr 25, 2018 3:42:43 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Offerta generated by hbm2java
 */
@Entity
@Table(name = "offerta", catalog = "db_inv_freel")
public class Offerta implements java.io.Serializable, entities.Entity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer rowId;
	private AnnuncioProgetto annuncioProgetto;
	private StatoOfferta statoOfferta;
	private Utente utente;
	private Double valore;
	private Date dataCreazione;
	private Date dataModifica;

	public Offerta() {
	}

	public Offerta(AnnuncioProgetto annuncioProgetto, Utente utente, Date dataCreazione, Date dataModifica) {
		this.annuncioProgetto = annuncioProgetto;
		this.utente = utente;
		this.dataCreazione = dataCreazione;
		this.dataModifica = dataModifica;
	}

	public Offerta(AnnuncioProgetto annuncioProgetto, StatoOfferta statoOfferta, Utente utente, Double valore,
			Date dataCreazione, Date dataModifica) {
		this.annuncioProgetto = annuncioProgetto;
		this.statoOfferta = statoOfferta;
		this.utente = utente;
		this.valore = valore;
		this.dataCreazione = dataCreazione;
		this.dataModifica = dataModifica;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ROW_ID", unique = true, nullable = false)
	public Integer getRowId() {
		return this.rowId;
	}

	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ANNUNCIO", nullable = false)
	public AnnuncioProgetto getAnnuncioProgetto() {
		return this.annuncioProgetto;
	}

	public void setAnnuncioProgetto(AnnuncioProgetto annuncioProgetto) {
		this.annuncioProgetto = annuncioProgetto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATO")
	public StatoOfferta getStatoOfferta() {
		return this.statoOfferta;
	}

	public void setStatoOfferta(StatoOfferta statoOfferta) {
		this.statoOfferta = statoOfferta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_OFFERENTE", nullable = false)
	public Utente getUtente() {
		return this.utente;
	}

	public void setUtente(Utente utente) {
		this.utente = utente;
	}

	@Column(name = "VALORE", precision = 22, scale = 0)
	public Double getValore() {
		return this.valore;
	}

	public void setValore(Double valore) {
		this.valore = valore;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_CREAZIONE", nullable = false, length = 19)
	public Date getDataCreazione() {
		return this.dataCreazione;
	}

	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_MODIFICA", nullable = false, length = 19)
	public Date getDataModifica() {
		return this.dataModifica;
	}

	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

}
