package entities;
// Generated Apr 25, 2018 3:42:43 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * StoricoProgetto generated by hbm2java
 */
@Entity
@Table(name = "storico_progetto", catalog = "db_inv_freel")
public class StoricoProgetto implements java.io.Serializable, entities.Entity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer rowId;
	private Utente utente;
	private StatoProgetto statoProgetto;
	private int idProgetto;
	private int idUtente;
	private String idSottoinsieme;
	private Date dataCreazione;

	public StoricoProgetto() {
	}

	public StoricoProgetto(Utente utente, StatoProgetto statoProgetto, int idProgetto, int idUtente,
			String idSottoinsieme, Date dataCreazione) {
		this.utente = utente;
		this.statoProgetto = statoProgetto;
		this.idProgetto = idProgetto;
		this.idUtente = idUtente;
		this.idSottoinsieme = idSottoinsieme;
		this.dataCreazione = dataCreazione;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "utente"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "ROW_ID", unique = true, nullable = false)
	public Integer getRowId() {
		return this.rowId;
	}

	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Utente getUtente() {
		return this.utente;
	}

	public void setUtente(Utente utente) {
		this.utente = utente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATO", nullable = false)
	public StatoProgetto getStatoProgetto() {
		return this.statoProgetto;
	}

	public void setStatoProgetto(StatoProgetto statoProgetto) {
		this.statoProgetto = statoProgetto;
	}

	@Column(name = "ID_PROGETTO", nullable = false)
	public int getIdProgetto() {
		return this.idProgetto;
	}

	public void setIdProgetto(int idProgetto) {
		this.idProgetto = idProgetto;
	}

	@Column(name = "ID_UTENTE", nullable = false)
	public int getIdUtente() {
		return this.idUtente;
	}

	public void setIdUtente(int idUtente) {
		this.idUtente = idUtente;
	}

	@Column(name = "ID_SOTTOINSIEME", nullable = false, length = 45)
	public String getIdSottoinsieme() {
		return this.idSottoinsieme;
	}

	public void setIdSottoinsieme(String idSottoinsieme) {
		this.idSottoinsieme = idSottoinsieme;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_CREAZIONE", nullable = false, length = 19)
	public Date getDataCreazione() {
		return this.dataCreazione;
	}

	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

}
