package entities;
// Generated Apr 25, 2018 3:42:43 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoUtente generated by hbm2java
 */
@Entity
@Table(name = "tipo_utente", catalog = "db_inv_freel")
public class TipoUtente implements java.io.Serializable, entities.Entity{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String tipo;
	private Set<UtenteSpecifico> utenteSpecificos = new HashSet<UtenteSpecifico>(0);

	public TipoUtente() {
	}

	public TipoUtente(String tipo) {
		this.tipo = tipo;
	}

	public TipoUtente(String tipo, Set<UtenteSpecifico> utenteSpecificos) {
		this.tipo = tipo;
		this.utenteSpecificos = utenteSpecificos;
	}

	@Id

	@Column(name = "TIPO", unique = true, nullable = false, length = 45)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoUtente")
	public Set<UtenteSpecifico> getUtenteSpecificos() {
		return this.utenteSpecificos;
	}

	public void setUtenteSpecificos(Set<UtenteSpecifico> utenteSpecificos) {
		this.utenteSpecificos = utenteSpecificos;
	}

}
