package entities;
// Generated Apr 25, 2018 3:42:43 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipologiaFattura generated by hbm2java
 */
@Entity
@Table(name = "tipologia_fattura", catalog = "db_inv_freel")
public class TipologiaFattura implements java.io.Serializable {

	private String tipologia;
	private Set<Fattura> fatturas = new HashSet<Fattura>(0);

	public TipologiaFattura() {
	}

	public TipologiaFattura(String tipologia) {
		this.tipologia = tipologia;
	}

	public TipologiaFattura(String tipologia, Set<Fattura> fatturas) {
		this.tipologia = tipologia;
		this.fatturas = fatturas;
	}

	@Id

	@Column(name = "TIPOLOGIA", unique = true, nullable = false, length = 45)
	public String getTipologia() {
		return this.tipologia;
	}

	public void setTipologia(String tipologia) {
		this.tipologia = tipologia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipologiaFattura")
	public Set<Fattura> getFatturas() {
		return this.fatturas;
	}

	public void setFatturas(Set<Fattura> fatturas) {
		this.fatturas = fatturas;
	}

}
