package entities;
// Generated Apr 25, 2018 3:42:43 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UtenteTagId generated by hbm2java
 */
@Embeddable
public class UtenteTagId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int rowIdUtente;
	private String nomeTag;

	public UtenteTagId() {
	}

	public UtenteTagId(int rowIdUtente, String nomeTag) {
		this.rowIdUtente = rowIdUtente;
		this.nomeTag = nomeTag;
	}

	@Column(name = "ROW_ID_UTENTE", nullable = false)
	public int getRowIdUtente() {
		return this.rowIdUtente;
	}

	public void setRowIdUtente(int rowIdUtente) {
		this.rowIdUtente = rowIdUtente;
	}

	@Column(name = "NOME_TAG", nullable = false, length = 45)
	public String getNomeTag() {
		return this.nomeTag;
	}

	public void setNomeTag(String nomeTag) {
		this.nomeTag = nomeTag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UtenteTagId))
			return false;
		UtenteTagId castOther = (UtenteTagId) other;

		return (this.getRowIdUtente() == castOther.getRowIdUtente())
				&& ((this.getNomeTag() == castOther.getNomeTag()) || (this.getNomeTag() != null
						&& castOther.getNomeTag() != null && this.getNomeTag().equals(castOther.getNomeTag())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRowIdUtente();
		result = 37 * result + (getNomeTag() == null ? 0 : this.getNomeTag().hashCode());
		return result;
	}

}
