package entities;
// Generated Apr 25, 2018 3:42:43 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UtenteTag generated by hbm2java
 */
@Entity
@Table(name = "utente_tag", catalog = "db_inv_freel")
public class UtenteTag implements java.io.Serializable {

	private UtenteTagId id;
	private Tag tag;
	private UtenteSpecifico utenteSpecifico;
	private Integer esperienza;

	public UtenteTag() {
	}

	public UtenteTag(UtenteTagId id, Tag tag, UtenteSpecifico utenteSpecifico) {
		this.id = id;
		this.tag = tag;
		this.utenteSpecifico = utenteSpecifico;
	}

	public UtenteTag(UtenteTagId id, Tag tag, UtenteSpecifico utenteSpecifico, Integer esperienza) {
		this.id = id;
		this.tag = tag;
		this.utenteSpecifico = utenteSpecifico;
		this.esperienza = esperienza;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "rowIdUtente", column = @Column(name = "ROW_ID_UTENTE", nullable = false)),
			@AttributeOverride(name = "nomeTag", column = @Column(name = "NOME_TAG", nullable = false, length = 45)) })
	public UtenteTagId getId() {
		return this.id;
	}

	public void setId(UtenteTagId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NOME_TAG", nullable = false, insertable = false, updatable = false)
	public Tag getTag() {
		return this.tag;
	}

	public void setTag(Tag tag) {
		this.tag = tag;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	
	@JoinColumn(name = "ROW_ID_UTENTE", referencedColumnName="ROW_ID_UTENTE", nullable = false, insertable = false, updatable = false)
	public UtenteSpecifico getUtenteSpecifico() {
		return this.utenteSpecifico;
	}

	public void setUtenteSpecifico(UtenteSpecifico utenteSpecifico) {
		this.utenteSpecifico = utenteSpecifico;
	}

	@Column(name = "ESPERIENZA")
	public Integer getEsperienza() {
		return this.esperienza;
	}

	public void setEsperienza(Integer esperienza) {
		this.esperienza = esperienza;
	}

}
