package entities;
// Generated Apr 25, 2018 3:42:43 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UtenteSpecificoId generated by hbm2java
 */
@Embeddable
public class UtenteSpecificoId implements java.io.Serializable {

	private int rowId;
	private int rowIdUtente;

	public UtenteSpecificoId() {
	}

	public UtenteSpecificoId(int rowId, int rowIdUtente) {
		this.rowId = rowId;
		this.rowIdUtente = rowIdUtente;
	}

	@Column(name = "ROW_ID", unique = true, nullable = false)
	public int getRowId() {
		return this.rowId;
	}

	public void setRowId(int rowId) {
		this.rowId = rowId;
	}

	@Column(name = "ROW_ID_UTENTE", nullable = false)
	public int getRowIdUtente() {
		return this.rowIdUtente;
	}

	public void setRowIdUtente(int rowIdUtente) {
		this.rowIdUtente = rowIdUtente;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UtenteSpecificoId))
			return false;
		UtenteSpecificoId castOther = (UtenteSpecificoId) other;

		return (this.getRowId() == castOther.getRowId()) && (this.getRowIdUtente() == castOther.getRowIdUtente());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRowId();
		result = 37 * result + this.getRowIdUtente();
		return result;
	}

}
